version: '3'
services:
  watermark:
    container_name: tardigrada/watermark
    image:
    volumes:
      - ./temp:/app/temp
      - ./sessions:/app/sessions
      - ./configuration.ini:/app/configuration.ini
    restart: always