version: '3'
services:
  watermark:
    container_name: watermark
    image: tardigrada/watermark:latest
    volumes:
      - ./temp:/app/temp
      - ./sessions:/app/sessions
      - ./configuration.ini:/app/configuration.ini
    restart: always